extend type Query {
  serverTypes(
    instanceOption: AwsInstanceOption!
    region: String!
  ): [ServerType!]!
}

# extend type Mutation {
# }

type ServerType {
  type: String!
  monthlyCost: Float!
}

enum AwsInstanceOption {
  OnDemand
  Spot
}
